### ISSUE TITLE
gdsdk.set_listener never runs the registered function

### ISSUE THREAD

**Issue by fabtjar** [GameDistribution/gd-defold#2]
I can play the ads but I'm not being told when they are finished as the `gdsdk.set_listener` function I register never runs.

I've tried this with the example project too and getting the same results.

There are errors in the console from `gamemonkey-sdk.js`.

Defold 1.4.8

**Comment by britzl** [comment]
@fabtjar I'm not able to reproduce this issue. Can you please try the example project which is included in this extension? Just open the extension as a normal Defold project and run it using Project -> Build HTML5. You will see that the listener is triggered, although it will not show any ads when running it locally like that.
